### ISSUE TITLE
debugpy launch-with-arguments: there can be only one

### ISSUE THREAD

**Issue by dmaziuk** [microsoft/vscode-python-debugger#465] opened 2024-09-27 22:48 UTC
Version: 1.93.1
OS: Windows 11

Similar to #233 only different: when passing more than a single command line arg via "Command Line Arguments" prompt, the whole string is wrapped in quotes and passed as a single arg. E.g. passing "-v" works, passing "-l logfile.log" breaks `argparse` or anything that expects those in separate elements in `sys.argv`

**Comment by eleanorjboyd** [comment] 2024-10-01 18:42
yes understood this seems to be an ongoing issue. In the meantime does doing "-l=logfile.log" help at all? Or no given you are attempting multiple arguments?

**Comment by dmaziuk** [comment] 2024-10-01 21:00
I usually need multiple arguments, yes.

It also won't work with combinations of switches e.g. `-a -b` and/or positional args `one two three` etc.

**Comment by karthiknadig** [comment] 2024-12-11 14:32
The `"${command:pickArgs}"` is actually implemented in VS Code. This should be fixed there.

Duplicate of: https://github.com/microsoft/vscode/issues/232560

**Closed by karthiknadig** 2024-12-11 14:32 UTC
Labels: bug, triage-needed
