### ISSUE TITLE
Debugger breaks in interactiveshell.py

### ISSUE THREAD

**Issue by maximilianmordig** [microsoft/vscode-python-debugger#374] opened 2024-07-05 07:08 UTC
Type: <b>Bug</b>

# Behaviour

Whenever I debug a cell in an interactive window, it first stops at the `interactiveshell.py` even though I have not set a breakpoint there, so I have to hit F5 to get to the actual breakpoint.
I generally use `justMyCode=False` because I also want to step into libraries, but only where I set breakpoints.
This is related to https://github.com/microsoft/vscode-jupyter/issues/9815, which is closed for comments.

## Steps to reproduce:

Debug a cell with `justMyCode=False`.

![image](https://github.com/microsoft/vscode-python-debugger/assets/10333470/4d1ab4b3-3722-4a2b-823b-c29b32360d0f)

![image](https://github.com/microsoft/vscode-python-debugger/assets/10333470/c78c78d1-56f2-430e-88fb-8ffbdb2ac18b)

# Diagnostic data

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

# Behaviour

XXX

## Steps to reproduce:

1. XXX

# Diagnostic data
<details>

<summary><code>launch.json</code> configuration
</summary>

<p>

```
XXX
```

</p>
</details>

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

<details>

<summary>Output for <code>Python Debugger</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python Debugger</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

Extension version: 2024.6.0
VS Code version: Code 1.90.2 (Universal) (5437499feb04f7a586f677b155b039bc2b3669eb, 2024-06-18T22:37:41.291Z)
OS version: Darwin arm64 22.6.0
Modes:
Remote OS version: Linux x64 6.2.0-36-generic
Connection to 'SSH: mikado' could not be established  Canceled
Connection to 'ssh-remote+mikado' could not be established
Connection to 'SSH: mikado' could not be established  Canceled
Remote OS version: Linux x64 6.2.0-36-generic

-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.12
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): VirtualEnvironment<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (12 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.21GB free)|
|Process Argv|--crash-reporter-id 3133677a-c9e5-4743-9d41-dd5ce026400a|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: mikado|
|OS|Linux x64 6.2.0-36-generic|
|CPUs|Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz (48 x 1200)|
|Memory (System)|125.80GB (114.32GB free)|
|VM|0%|

Connection to 'SSH: mikado' could not be established  Canceled

Connection to 'ssh-remote+mikado' could not be established

Connection to 'SSH: mikado' could not be established  Canceled

|Item|Value|
|---|---|
|Remote|SSH: mikado|
|OS|Linux x64 6.2.0-36-generic|
|CPUs|Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz (48 x 1200)|
|Memory (System)|125.80GB (114.32GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelc:31048052
dsvsc021:30996838
da93g388:31013173
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
legacy_priority:31082724

```

</details>

**Comment by paulacamargo25** [comment] 2024-07-18 05:00
Thanks for your bug report, any idea what is happening here @rchiodo?

**Comment by rchiodo** [comment] 2024-07-18 16:15
This is by design or really a side effect of just my code being off. The kernel is stepping through code and with just my code off this entry is hit. There's really no workaround without adding some sort of custom callstack filtering to debugpy for this exact situation. It would be like `stepThroughAllCodeExceptTheKernel` or something like that.

**Comment by paulacamargo25** [comment] 2024-07-27 00:12
Thanks @rchiodo, i am closing the issue since this is not handle in the Python debugger extension. Feel free to create a feature-request in https://github.com/microsoft/debugpy.

**Closed by paulacamargo25** 2024-07-27 00:12 UTC
Labels: triage-needed
