### ISSUE TITLE
"Debug using launch.json" tries to run the launch.json as a Python file

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-python-debugger#145] opened 2023-11-28 20:38 UTC
Testing #141

- Pick "Debug using launch.json"
- Pick "Python Debugger"
- The launch.json opens, and at the same time, the debugger starts on the launch.json file, and this fails
<img width="1152" alt="image" src="https://github.com/microsoft/vscode-python-debugger/assets/323878/07872efd-bb06-49fd-99e0-fb9cef146310">

**Comment by paulacamargo25** [comment] 2023-11-29 18:16
Duplicate of https://github.com/microsoft/vscode-python-debugger/issues/142

**Closed by paulacamargo25** 2023-11-29 18:16 UTC
Labels: triage-needed
