### ISSUE TITLE
matin

### ISSUE THREAD

**Issue by matinpodin12** [microsoft/vscode-python-debugger#376] opened 2024-07-07 22:20 UTC
Type: <b>Bug</b>

# Behaviour

XXX

## Steps to reproduce:

1. XXX

# Diagnostic data
<details>

<summary><code>launch.json</code> configuration
</summary>

<p>

```
XXX
```

</p>
</details>

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

<details>

<summary>Output for <code>Python Debugger</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python Debugger</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

# Behaviour

XXX

## Steps to reproduce:

1. XXX

# Diagnostic data
<details>

<summary><code>launch.json</code> configuration
</summary>

<p>

```
XXX
```

</p>
</details>

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

<details>

<summary>Output for <code>Python Debugger</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python Debugger</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

Extension version: 2024.6.0
VS Code version: Code 1.91.0 (ea1445cc7016315d0f5728f8e8b12a45dc0a7286, 2024-07-01T18:52:22.949Z)
OS version: Windows_NT x64 10.0.19045
Modes:

-   Python version (& distribution if applicable, e.g. Anaconda): 3.12.4
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Unknown<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz (8 x 2594)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (1.76GB free)|
|Process Argv|C:\\Users\\matin\\Desktop\\select.pyd --crash-reporter-id 56bd8403-bfcc-4f8c-8ab1-c2a21c4b146e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelc:31048052
dsvsc021:30996838
jg8ic977:31013176
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
legacy_priority:31082724

```

</details>

**Comment by brettcannon** [comment] 2024-07-08 16:59
Due to a lack of details of what the problem is, we are closing this issue. You can always open another issue if you are able to provide more details.

**Closed by brettcannon** 2024-07-08 16:59 UTC
Labels: triage-needed
