### ISSUE TITLE
Python Debugger fails to load Python3 if installed on a path with spaces

### ISSUE THREAD

**Issue by fgiancane8** [microsoft/vscode-python-debugger#351] opened 2024-05-29 12:01 UTC
# Behaviour

It is expected to be able to debug a python script or module using the globally installed Python runtime from their website. It turns out that if installed via their setup, it gets deployed in C:\Program Files\Python312. The path contains a space which should be escaped when loading it, but it is not, resulting in misleading errors and not being able of debugging.

## Steps to reproduce:

1. Select  "Start Debugging" (F5)
2. Select "Python Debugger"
3. Leave the command line empty
4. Observe command line failure

# Diagnostic data
<details>
<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>
<p>

```
PS C:\Users\fgiancan\source\repos\scripts>  c:; cd 'c:\Users\fgiancan\source\repos\scripts'; c:\Program Files\Python312\python.exe c:\Users\fgiancan\.vscode\extensions\ms-python.debugpy-2024.6.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher 63087 -- C:\Users\fgiancan\source\repos\scripts\test.py
c:\Program: The term 'c:\Program' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

</p>
</details>
<details>
<summary>Output for <code>Python Debugger</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python Debugger</code>)
</summary>
<p>

```
2024-05-29 12:34:57.789 [info] Experiment 'pythonRecommendTensorboardExt' is active
2024-05-29 12:34:57.789 [info] Experiment 'pythonREPLSmartSend' is active
2024-05-29 12:34:57.789 [info] Experiment 'pythonTerminalEnvVarActivation' is active
2024-05-29 12:34:57.789 [info] Experiment 'pythonTestAdapter' is active
2024-05-29 12:34:57.830 [info] Default formatter is set to null for workspace c:\Users\fgiancan\source\repos\scripts
2024-05-29 12:34:58.202 [info] > pyenv which python
2024-05-29 12:34:58.202 [info] cwd: .
2024-05-29 12:34:58.320 [info] > "c:\Program Files\Python312\python.exe" -I ~\.vscode\extensions\ms-python.python-2024.6.0\python_files\get_output_via_markers.py ~\.vscode\extensions\ms-python.python-2024.6.0\python_files\interpreterInfo.py
2024-05-29 12:35:01.402 [warning] Shell integration may not be active, environment activated may be overridden by the shell.
2024-05-29 12:35:02.368 [info] Python interpreter path: c:\Program Files\Python312\python.exe
2024-05-29 12:35:04.514 [info] Starting Pylance language server.
2024-05-29 12:35:06.331 [info] Shell integration status changed, can confirm it's working.
2024-05-29 12:40:58.375 [info] Python interpreter path: C:\Program Files\Python312\python.exe
2024-05-29 12:41:11.680 [info] Send text to terminal:  c:\Program Files\Python312\python.exe c:\Users\fgiancan\.vscode\extensions\ms-python.debugpy-2024.6.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher 63012 -- C:\Users\fgiancan\source\repos\scripts\test.py
2024-05-29 12:44:03.765 [info] Send text to terminal: 
2024-05-29 12:44:03.765 [info] Send text to terminal:  c:; cd 'c:\Users\fgiancan\source\repos\scripts'; c:\Program Files\Python312\python.exe c:\Users\fgiancan\.vscode\extensions\ms-python.debugpy-2024.6.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher 63087 -- C:\Users\fgiancan\source\repos\scripts\test.py
```

</p>
</details>

**Comment by paulacamargo25** [comment] 2024-05-30 20:52
Thanks for your bug report, could you send me the value of config in the `launch.json`? Thanks

**Comment by fgiancane8** [comment] 2024-05-31 10:21
I think the issue is related to the fact that the interpreter's path string is taken and is left unquoted, and thus it is not parsed after encountering the first space character. That explains why "C:\Program Files\Python312\" is truncated to C:\Program.

**Comment by roelandschoukens** [comment] 2024-06-05 05:28
You don’t need any launch.json file to reproduce this, just open a python file, press <kbd>F5</kbd>, select "Python File With Arguments", and you'll produce that error.

If you select "Python File" you'll see that the invocation on the PowerShell console has quotes:

`'c:\Program Files\Python312\python.exe' 'paht\to\launcher' '123456' '--' 'path\to\file.py'`

If you select "Python File with Arguments" you'll see that none of the paths have quotes:

`c:\Program Files\Python312\python.exe path\to\adapter/../..\debugpy\launcher 55814 -- path\to\file-ext.py --a --b --c `

(incidentally, to switch between those two, you'll need to do a "Python debugger: clear cache and reload window")

**Comment by fgiancane8** [comment] 2024-06-05 22:57
So this definitively confirms we have a bug here, right ?

**Comment by fgiancane8** [comment] 2024-06-10 19:39
@paulacamargo25 hello,
Do we have an update on this?

**Comment by paulacamargo25** [comment] 2024-06-13 20:29
Thanks @fgiancane8 for the bug report, yes, could you confirm that this is a duplicate of #233.

**Comment by fgiancane8** [comment] 2024-06-13 22:44
Hello @paulacamargo25 ,
It looks like is the same issue.

If needed we can discuss further there.

Thanks!

**Comment by paulacamargo25** [comment] 2024-06-13 22:53
Thanks, closed as duplicated of: https://github.com/microsoft/vscode-python-debugger/issues/233.

**Closed by paulacamargo25** 2024-06-13 22:53 UTC
Labels: triage-needed, info-needed

**Comment by fgiancane8** [comment] 2025-02-26 00:59
Sorry to comment further on a previously closed issue -- but I still have problems here.
In particular, 
```
"args": "${command:pickArgs}",
```
has a different behaviour with respect to
```
"args": ["${command:pickArgs}"],
```
In particular, in one case the full program command path (e.g. C:\Program Files\Python312\) does not get escaped, in the other case it gets proper escaping, causing Visual Studio Code to fail because of the spaces.

I don't know if ```args``` parameter cannot be specified in both these ways but I think that program path must be quoted the same way in both cases to avoid these kind of issues.

@karthiknadig @brettcannon is there any other information I can provide? I can paste my interpreter errors.

Thanks!

**Comment by brettcannon** [comment] 2025-02-26 23:12
I'm not on the team anymore, so I'll leave it to Karthik to reply.

**Comment by karthiknadig** [comment] 2025-02-26 23:48
Created https://github.com/microsoft/vscode-python-debugger/issues/635 to track this.
