### ISSUE TITLE
Error when trying to debug in version 2024.12.0

### ISSUE THREAD

**Issue by Ranzoni** [microsoft/vscode-python-debugger#488] opened 2024-10-21 18:01 UTC
If I just run my API and try to use it, it works. But the moment I put a breakpoint and I try to call the piece of code with it, an error is returned: "an integer is required".

But if I remove the breakpoint and restart the application, works again. The problem always happens if the interpreter calls the method with the breakpoint.

That not happens if I change the Python Debugger to version 2024.10.0.

I identify this problem in the API of the company I work for. Both on my computer and on my notebook. I haven't tested it with other applications.

**Comment by karthiknadig** [comment] 2024-10-21 22:07
@Ranzoni You seem to be hitting this errorhttps://github.com/microsoft/debugpy/issues/1708 which is in the `debugpy` package. The latest version of the debugger extension ships the latest debugpy which added support for python 3.13 and uses `sys.monitoring` API for debugging.

Closing as duplicate of: https://github.com/microsoft/debugpy/issues/1708

**Closed by karthiknadig** 2024-10-21 22:07 UTC
Labels: triage-needed
